
files:
  raw_dirs: ['/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_input_tstack',
             '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_input_tstack']

  supp_dirs: ['/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_supp_tstack',
              '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_supp_tstack']

  train_dirs: ['/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_train_tstack',
               '/CompMicro/projects/cardiomyocytes/20200722CM_LowMOI_SPS_Fluor/20200722 CM_LowMOI_SPS/dnm_train_tstack']

  model_dir: '/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_train_tstack/models'

  weights_dir: '/CompMicro/projects/cardiomyocytes/200721_CM_Mock_SPS_Fluor/20200721_CM_Mock_SPS/dnm_train_tstack/weights'


preprocess:
#  cs: [0, 1]
#  cs_mask: [2,3]
#  input_shape: (128, 128)
  w_a: 1
  w_t: 0.5
  channel_mean: [0.4, 0, 0.5]
  channel_std: [0.05, 0.05, 0.05]


inference:
  model: 'VQ_VAE_z16'
  weights: '/gpfs/CompMicro/projects/dynamorph/CellVAE/save_0005_bkp4.pt'
  gpus: 1
  fov: ['C5-Site_0','C5-Site_1']
  channels: [0,1,2]


training:
  model: 'VQ_VAE_z32'
  num_inputs: 2
  num_hiddens: 64
  num_residual_hiddens: 64
  num_residual_layers: 2
  num_embeddings: 512
  commitment_cost: 0.25
  alpha: 0.002
  epochs: 5000
  learning_rate: 0.0001
  batch_size: 96
  GPU: True
  GPU_ID: 3
  shuffle_data: False
  transform: True


  

